//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VetClinic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability and manage rooms for treatments and surgeries.
        /// </summary>
        public static string CheckAvail {
            get {
                return ResourceManager.GetString("CheckAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of all patients under care..
        /// </summary>
        public static string KeepTrack {
            get {
                return ResourceManager.GetString("KeepTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Appointments.
        /// </summary>
        public static string ManageAppointments {
            get {
                return ResourceManager.GetString("ManageAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Doctors.
        /// </summary>
        public static string ManageDoctors {
            get {
                return ResourceManager.GetString("ManageDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Patients.
        /// </summary>
        public static string ManagePatients {
            get {
                return ResourceManager.GetString("ManagePatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rooms.
        /// </summary>
        public static string ManageRooms {
            get {
                return ResourceManager.GetString("ManageRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule, view, and manage appointments for patients.
        /// </summary>
        public static string ScheduleView {
            get {
                return ResourceManager.GetString("ScheduleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet Clinic Management System.
        /// </summary>
        public static string VetClinicManagementSystem {
            get {
                return ResourceManager.GetString("VetClinicManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage all doctors working at the clinic..
        /// </summary>
        public static string ViewAndManage {
            get {
                return ResourceManager.GetString("ViewAndManage", resourceCulture);
            }
        }
    }
}
