//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VetClinic.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access detailed health histories and treatment plans for every pet in seconds..
        /// </summary>
        public static string AccessDetailed {
            get {
                return ResourceManager.GetString("AccessDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Room.
        /// </summary>
        public static string AddRoom {
            get {
                return ResourceManager.GetString("AddRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Management.
        /// </summary>
        public static string AppointmentManagement {
            get {
                return ResourceManager.GetString("AppointmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Scheduling.
        /// </summary>
        public static string AppointmentScheduling {
            get {
                return ResourceManager.GetString("AppointmentScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy Vets who love their pets.
        /// </summary>
        public static string BusyVets {
            get {
                return ResourceManager.GetString("BusyVets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check availability and manage rooms for treatments and surgeries.
        /// </summary>
        public static string CheckAvail {
            get {
                return ResourceManager.GetString("CheckAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive.
        /// </summary>
        public static string Comprehensive {
            get {
                return ResourceManager.GetString("Comprehensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        public static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficient tools to track, organize, and prioritize urgent cases, ensuring pets get the
        ///care they need right on time..
        /// </summary>
        public static string EfficientTools {
            get {
                return ResourceManager.GetString("EfficientTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiently organize and manage client bookings with real-time availability updates..
        /// </summary>
        public static string EffOrg {
            get {
                return ResourceManager.GetString("EffOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Emergencies with Ease.
        /// </summary>
        public static string EmergencyCases {
            get {
                return ResourceManager.GetString("EmergencyCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep track of all patients under care.
        /// </summary>
        public static string KeepTrack {
            get {
                return ResourceManager.GetString("KeepTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string LEARNMORE {
            get {
                return ResourceManager.GetString("LEARNMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage vet schefules and appointments, keeping your team and clients informed and prepared..
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all pet medical records in one covienient platform..
        /// </summary>
        public static string ManageAll {
            get {
                return ResourceManager.GetString("ManageAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Appointments.
        /// </summary>
        public static string ManageAppointments {
            get {
                return ResourceManager.GetString("ManageAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Doctors.
        /// </summary>
        public static string ManageDoctors {
            get {
                return ResourceManager.GetString("ManageDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Patients.
        /// </summary>
        public static string ManagePatients {
            get {
                return ResourceManager.GetString("ManagePatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rooms.
        /// </summary>
        public static string ManageRooms {
            get {
                return ResourceManager.GetString("ManageRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor staff schedules to avoid overlaps and delays..
        /// </summary>
        public static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized Schedules, Better Care.
        /// </summary>
        public static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Stafff.
        /// </summary>
        public static string OurStaff {
            get {
                return ResourceManager.GetString("OurStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our system streamilnes your clinic&apos;s operations so you can focus in delivering the best care for every pet..
        /// </summary>
        public static string OurSystem {
            get {
                return ResourceManager.GetString("OurSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our sytem streamlines operations, ensuring efficient scheduling, patient care, and record-keeping for veterinarians. We help clicics enhance productivity, improve client communication, and provide exceptional service to pets and their owners..
        /// </summary>
        public static string OurVeterinary {
            get {
                return ResourceManager.GetString("OurVeterinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Records.
        /// </summary>
        public static string PatientRecords {
            get {
                return ResourceManager.GetString("PatientRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Health.
        /// </summary>
        public static string PetHealth {
            get {
                return ResourceManager.GetString("PetHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Links.
        /// </summary>
        public static string QuickLinks {
            get {
                return ResourceManager.GetString("QuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reliable.
        /// </summary>
        public static string Reliable {
            get {
                return ResourceManager.GetString("Reliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Number.
        /// </summary>
        public static string RoomNumber {
            get {
                return ResourceManager.GetString("RoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule, view, and manage appointments for patients.
        /// </summary>
        public static string ScheduleView {
            get {
                return ResourceManager.GetString("ScheduleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify scheduling, patient records, and billing with a system designed to keep your clinic running smoothly. .
        /// </summary>
        public static string Simplify {
            get {
                return ResourceManager.GetString("Simplify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplify bookings with a system that ensures seamless scheduling for vets and clients..
        /// </summary>
        public static string Simplifybookings {
            get {
                return ResourceManager.GetString("Simplifybookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart.
        /// </summary>
        public static string Smart {
            get {
                return ResourceManager.GetString("Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Tools.
        /// </summary>
        public static string SmartTools {
            get {
                return ResourceManager.GetString("SmartTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solutions.
        /// </summary>
        public static string Solutions {
            get {
                return ResourceManager.GetString("Solutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That You Can.
        /// </summary>
        public static string ThatYouCan {
            get {
                return ResourceManager.GetString("ThatYouCan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust!.
        /// </summary>
        public static string Trust {
            get {
                return ResourceManager.GetString("Trust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again later or contact support..
        /// </summary>
        public static string Try {
            get {
                return ResourceManager.GetString("Try", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vet Clinic Management System.
        /// </summary>
        public static string VetClinicManagementSystem {
            get {
                return ResourceManager.GetString("VetClinicManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaterinary Care.
        /// </summary>
        public static string VeterinaryCare {
            get {
                return ResourceManager.GetString("VeterinaryCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage all doctors working at the clinic.
        /// </summary>
        public static string ViewAndManage {
            get {
                return ResourceManager.GetString("ViewAndManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are always ready to help you &amp; your pets.
        /// </summary>
        public static string WeAreAlways {
            get {
                return ResourceManager.GetString("WeAreAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide expert medical services for your pets, ensuring their health and well-being at every stage of life..
        /// </summary>
        public static string WeProvide {
            get {
                return ResourceManager.GetString("WeProvide", resourceCulture);
            }
        }
    }
}
